/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author j40688
 */
import javax.swing.*;
public class AccuseGUI extends javax.swing.JFrame {

    private String picture;
    
    String character;
    String room;
    String weapon;
    String deck[];
    
    public AccuseGUI() {

        deck = TurnGui.addPlayer1.deck.getConfidentialCards();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        accuseButton = new javax.swing.JButton();
        charactersBox = new javax.swing.JComboBox<>();
        roomBox = new javax.swing.JComboBox<>();
        weaponsBox = new javax.swing.JComboBox<>();
        personImage = new javax.swing.JLabel();
        roomImage = new javax.swing.JLabel();
        weaponImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(600, 200));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        accuseButton.setBackground(new java.awt.Color(0, 255, 204));
        accuseButton.setText("Accuse");
        accuseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accuseButtonActionPerformed(evt);
            }
        });

        charactersBox.setBackground(new java.awt.Color(0, 0, 204));
        charactersBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Col Mustard", "Mrs Scarlet", "Mr Green", "Mrs Peacock", "Mrs White", "Prof Plumb" }));
        charactersBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                charactersBoxItemStateChanged(evt);
            }
        });

        roomBox.setBackground(new java.awt.Color(0, 0, 204));
        roomBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ballroom", "Billiard Room", "Conservatory", "Dining Room", "Hall", "Kitchen", "Library", "Lounge", "Study" }));
        roomBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                roomBoxItemStateChanged(evt);
            }
        });

        weaponsBox.setBackground(new java.awt.Color(0, 0, 204));
        weaponsBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Candle Stick", "Knife", "Lead Pipe", "Revolver", "Rope", "Wrench" }));
        weaponsBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                weaponsBoxItemStateChanged(evt);
            }
        });

        personImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Characters/Col Mustard.jpg"))); // NOI18N

        roomImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Rooms/Ballroom.jpg"))); // NOI18N

        weaponImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Weapons/Candle Stick.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(charactersBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(personImage, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(accuseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(roomBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(42, 42, 42)
                        .addComponent(weaponsBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(roomImage, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(weaponImage, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(personImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roomImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(weaponImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(charactersBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roomBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weaponsBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(accuseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(201, 201, 201))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void charactersBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_charactersBoxItemStateChanged
          picture = (String)charactersBox.getSelectedItem();
          personImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Characters/" + picture + ".jpg")));
    }//GEN-LAST:event_charactersBoxItemStateChanged

    private void roomBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_roomBoxItemStateChanged
          picture = (String)roomBox.getSelectedItem();
          roomImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Rooms/" + picture + ".jpg")));
    }//GEN-LAST:event_roomBoxItemStateChanged

    private void weaponsBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_weaponsBoxItemStateChanged
          picture = (String)weaponsBox.getSelectedItem();
          weaponImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Weapons/" + picture + ".jpg")));
    }//GEN-LAST:event_weaponsBoxItemStateChanged

    private void accuseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accuseButtonActionPerformed
        character = (String)charactersBox.getSelectedItem();
        room = (String)roomBox.getSelectedItem();
        weapon = (String)weaponsBox.getSelectedItem();

        if(room.equals(deck[0]) && character.equals(deck[1]) && weapon.equals(deck[2]))
        {
            Winner winner = new Winner(TurnGui.addPlayer1);
            winner.setVisible(true);
        }
        
        else
        {
            Wrong wrong = new Wrong();
            wrong.setVisible(true);
            wrong.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            this.setVisible(false);
            TurnGui.addPlayer1.currentPlayer.setInPlay(false);
            
        }
        
    }//GEN-LAST:event_accuseButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accuseButton;
    public javax.swing.JComboBox<String> charactersBox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel personImage;
    private javax.swing.JComboBox<String> roomBox;
    public javax.swing.JLabel roomImage;
    public javax.swing.JLabel weaponImage;
    private javax.swing.JComboBox<String> weaponsBox;
    // End of variables declaration//GEN-END:variables
}
