/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author j40688
 */
public class ViewCardsGui extends javax.swing.JFrame {

    /**
     * Creates new form ViewCardsGui
     */
    
    private String character;
    AddPlayerGui addPlayer1; 
    String []characterCards;
    String []weaponCards;
    String []roomCards;
    int characterCount;
    int weaponCount;
    int roomCount;
    
    public ViewCardsGui(AddPlayerGui addPlayer) {
        
        addPlayer1 = addPlayer;
        
        for(int i = 0; i < addPlayer1.currentPlayer.roomCards.length; i++)
        {
            if(!(addPlayer1.currentPlayer.roomCards[i].equals("null")))
            {
                roomCount++;
            }

        }
        
        for(int i = 0; i < addPlayer1.currentPlayer.suspectCards.length; i++)
        {
            if(!(addPlayer1.currentPlayer.suspectCards[i].equals("null")))
            {
                characterCount++;
            }
        }
        
        for(int i = 0; i < addPlayer1.currentPlayer.weaponCards.length; i++)
        {
            if(!(addPlayer1.currentPlayer.weaponCards[i].equals("null")))
            {
                weaponCount++;
            }
        }
        
        roomCards = new String[roomCount];
        characterCards = new String[characterCount];
        weaponCards = new String[weaponCount];
        
        for (int i = 0; i < roomCount; i++)
        {
            if(!addPlayer1.currentPlayer.roomCards[i].equals("null"))
            {
                roomCards[i] = addPlayer1.currentPlayer.roomCards[i];
            }
        }
        
        for (int i = 0; i < characterCount; i++)
        {
            if(!addPlayer1.currentPlayer.suspectCards[i].equals("null"))
            {
                characterCards[i] = addPlayer1.currentPlayer.suspectCards[i];
            }
        }
        
        for (int i = 0; i < weaponCount; i++)
        {
            if(!addPlayer1.currentPlayer.weaponCards[i].equals("null"))
            {
                weaponCards[i] = addPlayer1.currentPlayer.weaponCards[i];
            }
        }
      
        
        initComponents();
        roomBox.setModel(new javax.swing.DefaultComboBoxModel<>(roomCards));
        characterBox.setModel(new javax.swing.DefaultComboBoxModel<>(characterCards));
        weaponBox.setModel(new javax.swing.DefaultComboBoxModel<>(weaponCards));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
  
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardHolder = new javax.swing.JPanel();
        personImage = new javax.swing.JLabel();
        roomImage = new javax.swing.JLabel();
        weaponImage = new javax.swing.JLabel();
        roomBox = new javax.swing.JComboBox<>();
        characterBox = new javax.swing.JComboBox<>();
        weaponBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cardHolder.setBackground(new java.awt.Color(0, 0, 0));

        personImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CardBack.png"))); // NOI18N

        roomImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CardBack.png"))); // NOI18N
        roomImage.setText("jLabel1");

        weaponImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CardBack.png"))); // NOI18N

        roomBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomBoxActionPerformed(evt);
            }
        });

        characterBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                characterBoxActionPerformed(evt);
            }
        });

        weaponBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weaponBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cardHolderLayout = new javax.swing.GroupLayout(cardHolder);
        cardHolder.setLayout(cardHolderLayout);
        cardHolderLayout.setHorizontalGroup(
            cardHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardHolderLayout.createSequentialGroup()
                .addGroup(cardHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardHolderLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(roomImage, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardHolderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(roomBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addGroup(cardHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardHolderLayout.createSequentialGroup()
                        .addComponent(personImage, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardHolderLayout.createSequentialGroup()
                        .addComponent(characterBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)))
                .addGroup(cardHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardHolderLayout.createSequentialGroup()
                        .addComponent(weaponImage, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardHolderLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(weaponBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
        );
        cardHolderLayout.setVerticalGroup(
            cardHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardHolderLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(cardHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personImage)
                    .addComponent(roomImage)
                    .addComponent(weaponImage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cardHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(characterBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weaponBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(134, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardHolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cardHolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void characterBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_characterBoxActionPerformed
  
 
        String picture = (String)characterBox.getSelectedItem();
        personImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Characters/" + picture + ".jpg")));
    }//GEN-LAST:event_characterBoxActionPerformed

    private void roomBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomBoxActionPerformed

        String picture = (String)roomBox.getSelectedItem();
        roomImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Rooms/" + picture + ".jpg")));
    }//GEN-LAST:event_roomBoxActionPerformed

    private void weaponBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weaponBoxActionPerformed
        String picture = (String)weaponBox.getSelectedItem();
        weaponImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Weapons/" + picture + ".jpg")));
    }//GEN-LAST:event_weaponBoxActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardHolder;
    private javax.swing.JComboBox<String> characterBox;
    private javax.swing.JLabel personImage;
    private javax.swing.JComboBox<String> roomBox;
    private javax.swing.JLabel roomImage;
    private javax.swing.JComboBox<String> weaponBox;
    private javax.swing.JLabel weaponImage;
    // End of variables declaration//GEN-END:variables
}
